### ISSUE TITLE
Cannot find type Microsoft.SqlServer.Management.Smo.Backup

### ISSUE THREAD

**Issue by bootrider** [sqlcollaborative/dbatools#2991]
### General Troubleshooting steps

- [ ] Verified running the latest release of dbatools? yes
- [ ] Verified errors are not related to permissions? yes
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)? NO :(

### Version Information

 - Operating System (Name|Version): windows 10
 - PowerShell Version: 5.1.15063.786
 - SQL Server (Edition|Version): SQL Server 2008R2 to SQL Server 2014

## Steps to Reproduce
copy the database from one server to another, but it seems that dbatools module (maybe powershell session in the computer) is not able to load the dll with the backup class.

I tried to perform that operation in another machine (brand new one) just installing the module, and it works perfectly.

### LOG:

[log.txt](https://github.com/sqlcollaborative/dbatools/files/1610545/log.txt)

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/dqrm6.png
### Problem to solve
I understand that this is not a a bug related directly with the module, but any suggestion or hint would be thanked.

**Comment by wsmelton** [comment]
Ensure you are not running any other module such as `sqlps` or `sqlserver` within your session on the machine. Either one of those can prevent the dbatools library from loading properly and/or cause conflicts with SMO libraries.

If you are not able to duplicate it on the same machine it will be difficult to determine the cause/issue.

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann - take a look at this log. 
@bootrider - do you have a slower machine or one that is under a lot of stress?

**Comment by potatoqualitee** [comment]
how super weird that it breaks in the middle tho

**Comment by FriedrichWeinmann** [comment]
Heya, looked at things but uncaught exceptions rarely are represented in the logs in a helpful manner.

That said, it looks indeed like the library was not imported correctly. In order to test this, please:
 - Start a new process
 - Run this code
```
$dbatools_serialimport = $true
```
 - Then import dbatools

It should now take a bit longer to import but you'll see the errors on library import.

**Comment by potatoqualitee** [comment]
Thanks, fred! 

Would it make sense to check for RAM usage being high or a slow CPU or somethin then automatically setting serial import?

**Comment by FriedrichWeinmann** [comment]
I don't think that makes a difference for this case and the test can be a bit expensive import-time-wise, so I'd really hate to do it.
Got an idea I'm testing out at the moment though that should solve the extension method from low performance issue.

**Comment by bootrider** [comment]
@potatoqualitee luckly this machine does not have issues regarding RAM (48 GB) and the CPU is under 1% (Intel Xeon CPU E%-1620 @ 3.50 Ghz)

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann actually figured it out! Please download the newest version. Should be fixed 👍

**Comment by bootrider** [comment]
@FriedrichWeinmann , I tried what you proposed: 

> 
    Start a new process
    Run this code
    $dbatools_serialimport = $true

    Then import dbatools

I got the following error:
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS U:\> $dbatools_serialimport = $true
PS U:\> Import-Module dbatools
Exception calling "Invoke" with "3" argument(s): "Unable to load one or more of the requested types. Retrieve the
LoaderExceptions property for more information."
At line:214 char:5
+     $scriptBlock.Invoke($script:PSModuleRoot, "$script:DllRoot\smo",  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CmdletInvocationException
```

**Comment by bootrider** [comment]
I just update to version 0.9.153. Same behavior.

**Comment by bootrider** [comment]
I just try the following and it works:

`PS C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.153\bin\smo> add-type -path .\Microsoft.SqlServer.SmoExtended.dll`

`PS C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.153\bin\smo> Import-Module dbatools`

**Comment by bootrider** [comment]
Any one have news regarding this issue?

it is still present in the version 0.9.369

I can confirm that in version 0.9.76 it does not happen

**Comment by potatoqualitee** [comment]
hey @bootrider - can you confirm this is still an issue for you? We were having slow loading issues around Jul 5. Everything should work now.

**Comment by potatoqualitee** [comment]
please open this bck up if it is indeed an issue. closing for now, cant repro.
