### ISSUE TITLE
[Bug] Export-DbaScript using ScriptBatchTerminator = $true results in empty files

### ISSUE THREAD

**Issue by caderoux** [sqlcollaborative/dbatools#5679]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.503                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.503                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834




```

#### SQL Server: 

```sql
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: ) (Hypervisor)

```

### Report

`Export-DbaScript` using `ScriptBatchTerminator = $true` results in empty files

#### Errors Received

None

#### Steps to Reproduce
```
param (
    [String] $ServerInstance = "localhost"
    ,[String] $Database = "msdb"
    ,[String] $Table = "dbo.msdb_version"
)

$options = New-DbaScriptingOption

$options.ScriptBatchTerminator = $false
$options.FileName = ".\GoodFile.sql"
Get-DbaDbTable -SqlInstance $ServerInstance -Database $Database -Table $Table |
    Export-DbaScript -ScriptingOptionsObject $options -Path $options.FileName

$options.ScriptBatchTerminator = $true
$options.FileName = ".\BadFile.sql"
Get-DbaDbTable -SqlInstance $ServerInstance -Database $Database -Table $Table |
    Export-DbaScript -ScriptingOptionsObject $options -Path $options.FileName
```

#### Expected Behavior

Generate scripts

#### Actual Behavior

One script is empty when ScriptBatchTerminator = $true

**Comment by wsmelton** [comment]
This seems to be associated with the parameter `-BatchSeparator` and the logic we have for building the script object. It does not account for when the script object is passed in. In some way we are overwriting or possibly just corrupting the scripting settings that are expected.

**Comment by potatoqualitee** [comment]
Please check prerelease and let me know if that fixes your issue 👍  It fixes a couple otehrs so i merged

**Comment by caderoux** [comment]
I think this fixes it.  There is an unrelated issue with the SET options and line breaks, I will have to investigate and submit a separate bug on that.

**Comment by potatoqualitee** [comment]
thanks so much

**Comment by caderoux** [comment]
Nope, I'm still seeing the same behavior with the test case above, but I'm not sure I removed and installed from prerelease quite right.

```
param (
    [String] $ServerInstance = "localhost"
    ,[String] $Database = "msdb"
    ,[String] $Table = "dbo.msdb_version"
)

$options = New-DbaScriptingOption

$options.ScriptBatchTerminator = $false
$options.FileName = ".\GoodFile.sql"
Get-DbaDbTable -SqlInstance $ServerInstance -Database $Database -Table $Table |
    Export-DbaScript -ScriptingOptionsObject $options -Path $options.FileName

$options.ScriptBatchTerminator = $true
$options.FileName = ".\BadFile.sql"
Get-DbaDbTable -SqlInstance $ServerInstance -Database $Database -Table $Table |
    Export-DbaScript -ScriptingOptionsObject $options -Path $options.FileName

```

Gives:

GoodFile:

```
/*
	Created by DESKTOP-PIUB89R\Cade Roux using dbatools Export-DbaScript for objects on localhost$SQL2014 at 06/08/2019 16:55:13
	See https://dbatools.io/Export-DbaScript for more information
*/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[msdb_version](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[version_string] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[version_major] [int] NOT NULL,
	[version_minor] [int] NOT NULL,
	[version_build] [int] NOT NULL,
	[version_revision] [int] NOT NULL
) ON [PRIMARY]


```
BadFile:

```
/*
	Created by DESKTOP-PIUB89R\Cade Roux using dbatools Export-DbaScript for objects on localhost$SQL2014 at 06/08/2019 16:55:14
	See https://dbatools.io/Export-DbaScript for more information
*/

```

**Comment by potatoqualitee** [comment]
🤔  prerelease does not work the same way, since Path was changed. Got a few more changes to make, this will be enough to address the issue, thank you.

**Comment by potatoqualitee** [comment]
man i literally have no idea. i just tried all kinds of ways and cannot figure out a way to get this to work. i'm leaning bug but i'm not entirely convinced. the sample code i found on the web lead to @ClaudioESSilva's export-sqluser LOL

this is the last bug of the home stretch - claudio you got it in you? i just tried to no avail 👎

**Comment by ClaudioESSilva** [comment]
I also start to think this is a bug @potatoqualitee . Tried a bunch of combinations and having the `$options.ScriptBatchTerminator = $true` leads to strange outputs.

I will try to dig a little bit more (after DataGrillen) but in the meantime, @caderoux you can workaround using the `-BatchSeparator` parameter.

``` powershell
param (
    [String] $ServerInstance = "localhost"
    ,[String] $Database = "msdb"
    ,[String] $Table = "dbo.msdb_version"
)

$options = New-DbaScriptingOption

$options.ScriptBatchTerminator = $false
$options.FileName = ".\GoodFile.sql"
Get-DbaDbTable -SqlInstance $ServerInstance -Database $Database -Table $Table |
    Export-DbaScript -ScriptingOptionsObject $options -Path $options.FileName -BatchSeparator "GO"
```
This will give you a nice formated output.

```
/*
	Created by Laptop1\Claudio Silva using dbatools Export-DbaScript for objects on Laptop1 at 06/18/2019 13:04:55
	See https://dbatools.io/Export-DbaScript for more information
*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[msdb_version](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[version_string] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[version_major] [int] NOT NULL,
	[version_minor] [int] NOT NULL,
	[version_build] [int] NOT NULL,
	[version_revision] [int] NOT NULL
) ON [PRIMARY]

GO
```

**Comment by potatoqualitee** [comment]
thanks claudio!

**Comment by sqllensman** [comment]
I have had changes to resolve this issue that I wasn't able to complete due to work pressure.

Pull request has been created.

**Comment by ClaudioESSilva** [comment]
Thanks @sqllensman!
