### ISSUE TITLE
Invoke-DbaDiagnosticQuery - no queries run

### ISSUE THREAD

**Issue by jonantoine** [sqlcollaborative/dbatools#6787]
I am new to these tools, but I attempted to run the Invoke-DbaDiagnosticQuery command but it seems like no queries run and no data is collected.
If I try the use the -UseSelectionHelper flag I get no queries to select in the UI as well.
Below is the verbose output I get from the command.

```
Invoke-DbaDiagnosticQuery -SqlInstance xxxxxx -SqlCredential $Credential -v               
VERBOSE: [10:29:17][Invoke-DbaDiagnosticQuery] Interpreting DMV Script Collections
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2005.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2008.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2008R2.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2012.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2014.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2016.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2016SP1.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2016SP2.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2017.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_2019.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_AzureSQLDatabase.sql
VERBOSE: Parsing file C:\Program
Files\WindowsPowerShell\Modules\dbatools\1.0.116\bin\diagnosticquery\SQLServerDiagnosticQueries_SQLManagedInstance.sql
VERBOSE: [10:29:17][Invoke-DbaDiagnosticQuery] Collecting diagnostic query data from server: xxxxx
VERBOSE: Performing the operation "" on target "xxxxx".
VERBOSE: [10:29:18][Invoke-DbaDiagnosticQuery] Processed  on xxxxx


ComputerName     : xxxxx
InstanceName     : MSSQLSERVER
SqlInstance      : xxxxx
Number           : 0
Name             :
Description      :
DatabaseSpecific : False
Database         :
Notes            : Empty Result for this Query
Result           :

VERBOSE: [10:29:18][Invoke-DbaDiagnosticQuery] Empty result for Query 0 -  -
```
**Update**
I have tried installing on another computer and when I run the command on that machine I still get the same results. Am I installing the tools wrong?

**Comment by wsmelton** [comment]
Reported here #6653

**Comment by jpomfret** [comment]
@wsmelton - believe the issue was a change in the diag query files - I've created a PR if you could review :)

**Comment by wsmelton** [comment]
Our build process is to drop those files and pull them down using [Save-DbaDiagnosticQueryScript](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Save-DbaDiagnosticQueryScript.ps1). So likely best to take a look at that command and see why we are now pulling down the wrong files.

**Comment by jpomfret** [comment]
Pretty sure I've fixed it now, tests are running on #6845 right now

**Comment by MikeyBronowski** [comment]
I have an observation. Had the same issue as @jonantoine , even though I've got a newer version of the module with @jpomfret fix.

Today I did this with the latest version:

1. Test if the function works
`Invoke-DbaDiagnosticQuery -SqlInstance $server -UseSelectionHelper`

I've got no names...

2. Ran the Save function to get the latest version
`Save-DbaDiagnosticQueryScript`

The files got downloaded to MyDocuments folder instead of dbatools (my assumption would be to put it into **bin\diagnosticquery**

3. Finally, ran the Save-* with path to the existing queries
`Save-DbaDiagnosticQueryScript -Verbose -Path .\dbatools\bin\diagnosticquery`

That did the trick, so now step no 1 shows me the names.
Not sure if that's only me, but seems like in order to use the latest version of the scripts we need to do extra work which is not documented.

Extra thing (calling @andrekamman  as an author), 
https://docs.dbatools.io/#Save-DbaDiagnosticQueryScript

says 

```
Description
The dbatools module will have the diagnostic queries pre-installed. Use this only to update to a more recent version or specific versions.
```
How can we update to the specific version?

```
This function is mainly used by Invoke-DbaDiagnosticQuery, but can also be used independently to download the Glenn Berry DMV scripts.

Use this function to pre-download the scripts from a device with an Internet connection.
```
I cannot find a reference to Save- in Invoke-, so I am not sure if that works as described.

```
The function Invoke-DbaDiagnosticQuery will try to download these scripts automatically, but it obviously needs an internet connection to do that.
```
Automatic download of the latest script would be awesome, however, I cannot see it working.

**Comment by wsmelton** [comment]
@MikeyBronowski Save command defaults to saving to your documents folder:

https://github.com/sqlcollaborative/dbatools/blob/05fbf9898caf3922d1c9bf8017465bd57e5d387a/functions/Save-DbaDiagnosticQueryScript.ps1#L41-L44

These scripts don't serve the same functionality as with something like First Responder Kit and folks will alter them for their environments. 

Download ability is very limited because of the way Glenn publishes the scripts. We are basically scrapping [this site](https://glennsqlperformance.com/resources/) for the query file links and pulling them down.

You can update the help if you'd like to be more clear as to what it does.

If there are features or things missing please open a new issue.

**Comment by MikeyBronowski** [comment]
Cool. Wanted to make sure my experience is not unusual. Will have a look at the documentation.

**Comment by MikeyBronowski** [comment]
Btw. The changes did not resolve the issue described above, hence my comment here.

**Comment by jpomfret** [comment]
Agreed with @MikeyBronowski - this isn't working for me either...

Downloaded 1.0.124 from the gallery, `import-module dbatools`, and then `Invoke-DbaDiagnosticQuery -SqlInstance mssql1 -UseSelectionHelper` and I get no queries too choose.

Issue is the sql file is full of not sql - I believe it's the notebook file named .sql
https://github.com/sqlcollaborative/dbatools/blob/development/bin/diagnosticquery/SQLServerDiagnosticQueries_2017.sql

Running `Save-DbaDiagnosticQueryScript -Path C:\temp\glenn\` I get SQL files and it works fine from there.

**Comment by jpomfret** [comment]
Seems like that file has been bad for a while... July 3rd it changed from being sql to the notebook/json stuff
https://github.com/sqlcollaborative/dbatools/blob/0c24b88402d186fa770024e7733950e1633eeed6/bin/diagnosticquery/SQLServerDiagnosticQueries_2017.sql

@wsmelton or @potatoqualitee - how does bin\diagnosticquery get populated? I'm having trouble replicating the issue with downloading files...

**Comment by wsmelton** [comment]
It's a manual process done as part of the build process.

**Comment by wsmelton** [comment]
Once the gallery is back and up and functioning fully we can work on getting that build process setup in an Action. (Think @potatoqualitee knows a bit more about them now 🥳 )

**Comment by jpomfret** [comment]
Sounds awesome! The save command seems to work fine, so hopefully we can roll that in. 😊

**Comment by jpomfret** [comment]
This is now fixed in 1.0.125- @potatoqualitee saved out the files and published a new module version.
![image](https://user-images.githubusercontent.com/981370/96336533-687bdd00-1078-11eb-94ec-d986a396569b.png)
